pub mod compiler;
pub mod errors;
pub mod intepreter;
pub mod parser;
pub mod scanner;
mod conjunction;
mod datatype;
mod environment;
mod evaluation;
mod intermediate;
mod phrase;
mod precedent;
mod prefix;
mod primitive;
mod routine;
mod source;
mod statement;
mod std;
mod substantive;
mod token;
mod variable;
mod verb;
