pub mod compiler;
pub mod parser;
pub mod scanner;
pub mod errors;
mod source;
mod intermediate;
mod datatype;
mod phrase;
mod primitive;
mod conjunction;
mod precedent;
mod prefix;
mod verb;
mod statement;
mod token;