pub mod compiler;
pub mod intepreter;
pub mod parser;
pub mod scanner;
pub mod errors;
mod source;
mod intermediate;
mod datatype;
mod routine;
mod phrase;
mod environment;
mod evaluation;
mod primitive;
mod conjunction;
mod precedent;
mod prefix;
mod verb;
mod statement;
mod token;